### ISSUE TITLE
Finishing up on left-over APIs

### ISSUE THREAD

**Issue by wonyk** [rootkie/react-express-js-upstars#73]
They include:
1. Overall Stats counter
2. Clone class to suit next year
etc..

**Comment by rootkie** [comment]
A couple of APIs seems to be broken. Integration tests have 9 failed. Not sure if it's my setup's problem.

**Comment by rootkie** [comment]
Example: admin get pending/suspended/deleted people returns a JSON object but your tests are expecting array. Not sure if your tests type is wrong or backend code is wrong.

**Comment by wonyk** [comment]
The whole test is in series so if the first test fails, most likely the tests behind will also fail. To debug, Jest allows for the command line option to *bail* and stop the test once any of the tests fails. 

Just to confirm did you test on the new branch (v0.5.0-beta) or the current one in master?

**Comment by wonyk** [comment]
From another look, it seems like common tests that might fail in various machines are these:
1. registration working **(5951ms)**
2. Recreating new account for deleted users **(5199ms)**
3. Password Changes > proper requests returns success **(4442ms)**

They hit close to the 5000 ms limit default by Jest and will fail once the timing exceeds. 
However, currently, the long response time is due to the inclusion of Email sending, of which should the email fails to send (preventing users from "confirming" their email), they cannot log in.

Thus, the proposal is to adopt standard practice in the next coming commit or so to allow "Unverified Users" to login but constantly prompt them in the front-end to confirm their email and update account details.

**Comment by wonyk** [comment]
Refer to commit 2df1021 and issue #74. This solved the issue of long response timing by putting the sending of email as a lower priority then assuring the User the creation of account is complete.

Users can always request for new verification links so that they won't face the issues that they can't login.
